// Amazon Affiliate Products Database
// Tracking ID: brandonmills.com-20

export interface AffiliateProduct {
  id: string
  name: string
  slug: string
  brand: string
  category: string
  price: number
  originalPrice?: number
  rating: number
  reviewCount: number
  inStock: boolean
  amazonUrl: string
  images: string[]
  description: string
  features: string[]
  specs: Record<string, string>
  benefits: string[]
  forWhom: string[]
  featured?: boolean
}

const AFFILIATE_TAG = 'brandonmills.com-20'

export const affiliateProducts: AffiliateProduct[] = [
  // BEAUTY & SKINCARE
  {
    id: 'braun-ipl-pro-7',
    slug: 'braun-ipl-laser-hair-removal',
    name: 'Braun IPL at Home Laser Hair Removal for Women and Men, Silk Expert Pro 7',
    brand: 'Braun',
    category: 'Beauty & Personal Care',
    price: 499.99,
    originalPrice: 699.99,
    rating: 4.5,
    reviewCount: 12847,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Braun-i%C2%B7expert-Removal-Holiday-Trimmer/dp/B0CMVPMPZ8?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&q=80'],
    description: `The Braun Silk Expert Pro 7 is the world's #1 IPL device, offering professional-grade at-home laser hair removal for both women and men. With advanced SensoAdapt technology and 400,000 flashes, achieve permanent visible hair reduction in just 4 weeks.`,
    features: [
      'SensoAdapt™ Technology - Continuously adapts to your skin tone for optimal efficacy and safety',
      '400,000 Flashes - Enough for over 22 years of full body treatments',
      '10 Intensity Levels - Customizable power for different body areas and skin sensitivities',
      'Ultra-Fast Treatment - Largest flash window (4cm²) covers more skin per flash',
      'Precision Head Included - Ideal for face, bikini line, and sensitive areas',
      'Cordless & Rechargeable - Freedom to treat anywhere without being tethered',
      'Dermatologist Recommended - Clinically tested for safety and effectiveness',
      'FDA Cleared - Meets strict medical device standards',
    ],
    specs: {
      'Flash Window Size': '4 cm²',
      'Total Flashes': '400,000',
      'Intensity Levels': '10 adjustable settings',
      'Power Source': 'Rechargeable battery',
      'Treatment Time': 'Full body in ~20 minutes',
      'Skin Tone Compatibility': 'Light to medium brown (Fitzpatrick I-V)',
      'Hair Color Compatibility': 'Dark blonde to black',
      'Warranty': '2 years manufacturer warranty',
      'Package Includes': 'Main device, precision head, Venus razor, storage pouch, power adapter',
    },
    benefits: [
      'Permanent Visible Hair Reduction - FDA-cleared IPL technology targets hair follicles',
      'Professional Results at Home - Save thousands vs salon laser treatments',
      'Safe for All Genders - Effective on face and body for both women and men',
      'Pain-Free Experience - Gentle flashes with minimal discomfort (rated 2/10 pain level)',
      'Long-Term Investment - Device lasts 22+ years with proper use',
      'Clinically Proven - 92% of users report significant hair reduction in 4 weeks',
      'Convenient & Private - Treat on your own schedule in the comfort of home',
      'Cost Effective - ~$500 vs $3,000+ for professional laser sessions',
    ],
    forWhom: [
      'Women seeking permanent hair removal for legs, arms, underarms, bikini line, and face',
      'Men wanting to reduce chest, back, shoulder, and facial hair',
      'Anyone tired of shaving, waxing, or threading every few days',
      'People with light to medium skin tones and dark hair (most effective)',
      'Those seeking professional results without salon appointments',
      'Busy professionals who value time-saving beauty routines',
      'Anyone looking for a one-time investment vs recurring salon costs',
    ],
    featured: true,
  },
  {
    id: 'la-mer-creme',
    slug: 'la-mer-moisturizing-cream',
    name: 'La Mer The Moisturizing Cream',
    brand: 'La Mer',
    category: 'Luxury Skincare',
    price: 380.00,
    originalPrice: 420.00,
    rating: 4.6,
    reviewCount: 3421,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Mer-Moisturizing-Cream-Ounce/dp/B000C1XWN0?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80'],
    description: 'The legendary Crème de la Mer. A transformative cream that renews skin with natural sea-sourced Miracle Broth™. The ultimate luxury in skincare.',
    features: [
      'Miracle Broth™ - Sea-sourced fermented ingredients for skin renewal',
      'Deep Hydration - 12-hour moisture barrier protection',
      'Reduces Fine Lines - Visibly smooths and firms skin texture',
      'Calms Inflammation - Soothes redness and irritation',
      'Lightweight Texture - Absorbs quickly without heaviness',
    ],
    specs: {
      'Size': '2 oz (60ml)',
      'Skin Type': 'All skin types',
      'Key Ingredients': 'Sea Kelp, Vitamins, Minerals',
      'Application': 'Morning and evening',
      'Origin': 'Made in USA',
    },
    benefits: [
      'Iconic luxury skincare trusted by celebrities and dermatologists',
      'Transformative results with visible skin renewal',
      'Long-lasting hydration for plump, dewy skin',
      'Investment piece - small amount goes a long way',
    ],
    forWhom: [
      'Skincare enthusiasts seeking the ultimate luxury',
      'Mature skin requiring intensive hydration',
      'Anyone wanting visible anti-aging results',
      'Those who appreciate premium, time-tested formulations',
    ],
    featured: true,
  },
  {
    id: 'skinceuticals-ce-ferulic',
    slug: 'skinceuticals-vitamin-c-serum',
    name: 'SkinCeuticals C E Ferulic Vitamin C Antioxidant Serum',
    brand: 'SkinCeuticals',
    category: 'Luxury Skincare',
    price: 182.00,
    rating: 4.7,
    reviewCount: 8934,
    inStock: true,
    amazonUrl: `https://www.amazon.com/SkinCeuticals-Ferulic-Vitamin-Antioxidant-Serum/dp/B00AA8D8U0?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800&q=80'],
    description: 'The gold standard in vitamin C serums. Clinically proven to reduce fine lines, firm skin, and brighten complexion with 15% pure vitamin C.',
    features: [
      '15% L-Ascorbic Acid - Pure vitamin C for maximum efficacy',
      '1% Vitamin E - Neutralizes free radicals',
      '0.5% Ferulic Acid - Boosts antioxidant protection',
      'Photoprotection - Shields skin from UV damage',
      'Clinically Proven - 8 years of research and testing',
    ],
    specs: {
      'Size': '1 oz (30ml)',
      'pH Level': '2.0-3.5',
      'Concentration': '15% L-Ascorbic Acid',
      'Application': 'Once daily in morning',
      'Shelf Life': '3-6 months after opening',
    },
    benefits: [
      'Dermatologist-recommended #1 vitamin C serum',
      'Reduces fine lines and wrinkles in 12 weeks',
      'Brightens and evens skin tone',
      'Provides advanced environmental protection',
    ],
    forWhom: [
      'Anyone serious about anti-aging skincare',
      'Those with sun damage or hyperpigmentation',
      'Skincare minimalists wanting one powerful product',
      'People seeking clinically-proven results',
    ],
    featured: true,
  },

  // TECH & ELECTRONICS
  {
    id: 'macbook-pro-16-m3-max',
    slug: 'macbook-pro-16-m3-max',
    name: 'Apple MacBook Pro 16-inch M3 Max Chip, 48GB RAM, 1TB SSD',
    brand: 'Apple',
    category: 'Technology',
    price: 3999.00,
    rating: 4.9,
    reviewCount: 2145,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Apple-MacBook-Laptop-12%E2%80%91core-30%E2%80%91core/dp/B0CM5JV268?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80'],
    description: 'The most powerful MacBook Pro ever. M3 Max chip delivers unprecedented performance for creative professionals. Stunning Liquid Retina XDR display.',
    features: [
      'M3 Max Chip - 16-core CPU, 40-core GPU for extreme performance',
      '48GB Unified Memory - Handle massive projects effortlessly',
      '1TB SSD Storage - Lightning-fast read/write speeds',
      '16.2" Liquid Retina XDR - ProMotion 120Hz, 1000 nits sustained brightness',
      '22-Hour Battery Life - All-day power for intensive work',
      'Advanced Connectivity - 3x Thunderbolt 4, HDMI, SDXC card slot',
    ],
    specs: {
      'Processor': 'Apple M3 Max (16-core CPU, 40-core GPU)',
      'RAM': '48GB unified memory',
      'Storage': '1TB SSD',
      'Display': '16.2" Liquid Retina XDR (3456x2234)',
      'Weight': '4.8 lbs',
      'Ports': '3x Thunderbolt 4, HDMI, MagSafe 3, headphone jack',
    },
    benefits: [
      'Professional-grade performance for video editing, 3D rendering, music production',
      'Industry-leading display for color-accurate work',
      'Future-proof investment with Apple Silicon architecture',
      'Seamless integration with iPhone, iPad, and Apple ecosystem',
    ],
    forWhom: [
      'Content creators and video editors',
      'Photographers and graphic designers',
      'Music producers and audio engineers',
      'Developers working on intensive projects',
      'Anyone demanding the absolute best performance',
    ],
    featured: true,
  },
  {
    id: 'iphone-16-pro-max',
    slug: 'iphone-16-pro-max',
    name: 'Apple iPhone 16 Pro Max, 512GB, Natural Titanium',
    brand: 'Apple',
    category: 'Technology',
    price: 1399.00,
    rating: 4.8,
    reviewCount: 12567,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Apple-iPhone-512GB-Natural-Titanium/dp/B0DGZR5G18?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80'],
    description: 'The pinnacle of smartphone technology. A18 Pro chip, 48MP camera system, and titanium design. Pro-level photography and videography in your pocket.',
    features: [
      'A18 Pro Chip - Fastest smartphone processor ever',
      '48MP Main Camera - ProRAW, ProRes video, Spatial photos',
      'Titanium Design - Strongest, lightest iPhone ever',
      '6.9" Super Retina XDR - Always-On display, ProMotion 120Hz',
      '512GB Storage - Massive capacity for photos, videos, apps',
      'USB-C - Universal connectivity with 10Gbps transfer speeds',
    ],
    specs: {
      'Processor': 'A18 Pro chip',
      'Display': '6.9" Super Retina XDR OLED',
      'Camera': '48MP Main, 48MP Ultra Wide, 12MP Telephoto (5x optical zoom)',
      'Storage': '512GB',
      'Battery': 'Up to 29 hours video playback',
      'Materials': 'Titanium frame, Ceramic Shield front',
    },
    benefits: [
      'Pro-level photography and 4K ProRes video recording',
      'All-day battery life with fast charging',
      'Premium titanium build - lightweight and incredibly durable',
      'Future-proof with latest A18 Pro chip and iOS updates',
    ],
    forWhom: [
      'Mobile photographers and videographers',
      'Content creators who shoot on iPhone',
      'Power users needing maximum storage',
      'Anyone wanting the absolute best iPhone',
    ],
    featured: true,
  },

  // PHOTOGRAPHY & STUDIO
  {
    id: 'godox-sl60w',
    slug: 'godox-led-video-light',
    name: 'Godox SL60W LED Video Light, 60W 5600K Daylight Balanced',
    brand: 'Godox',
    category: 'Photo & Video',
    price: 119.00,
    rating: 4.6,
    reviewCount: 4231,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Godox-SL-60W-5600K-Bowens/dp/B01M0Z4H29?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80'],
    description: 'Professional continuous LED lighting for photography and videography. 60W output with Bowens mount for versatile light shaping.',
    features: [
      '60W LED Output - Powerful, consistent daylight-balanced light',
      'Bowens Mount - Compatible with thousands of light modifiers',
      'Quiet Cooling - Silent operation for video recording',
      'Remote Control - Wireless brightness adjustment',
      'CRI 95+ - Accurate color reproduction',
    ],
    specs: {
      'Power': '60W LED',
      'Color Temperature': '5600K ±300K',
      'CRI': '95+',
      'Dimming Range': '10%-100%',
      'Mount': 'Bowens S-type',
      'Power Supply': 'AC adapter included',
    },
    benefits: [
      'Professional studio-quality light at affordable price',
      'Perfect for portraits, product photography, YouTube videos',
      'Versatile with softboxes, reflectors, and modifiers',
      'Constant output - no flicker for video work',
    ],
    forWhom: [
      'YouTubers and content creators',
      'Portrait photographers',
      'Product photographers',
      'Anyone building a home studio',
    ],
    featured: true,
  },

  // PHILOSOPHY & BOOKS
  {
    id: 'atomic-habits',
    slug: 'atomic-habits-book',
    name: 'Atomic Habits by James Clear',
    brand: 'Avery',
    category: 'Philosophy & Books',
    price: 13.99,
    originalPrice: 27.00,
    rating: 4.8,
    reviewCount: 87432,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80'],
    description: 'Transform your life with tiny changes that deliver remarkable results. The definitive guide to habit formation from bestselling author James Clear.',
    features: [
      'Proven Framework - 4 Laws of Behavior Change',
      'Practical Strategies - Actionable steps for habit building',
      'Science-Backed - Research on habit psychology and neuroscience',
      'Real Examples - Stories from Olympic athletes, CEOs, artists',
    ],
    specs: {
      'Format': 'Hardcover',
      'Pages': '320 pages',
      'Publisher': 'Avery',
      'Language': 'English',
      'Dimensions': '6.4 x 1.1 x 9.6 inches',
    },
    benefits: [
      'Build good habits that stick and break bad ones',
      'Master tiny behaviors that lead to remarkable results',
      'Overcome lack of motivation and willpower',
      'Design your environment for success',
    ],
    forWhom: [
      'Anyone wanting to improve their habits',
      'Entrepreneurs and high performers',
      'People struggling with consistency',
      'Self-improvement enthusiasts',
    ],
    featured: true,
  },
  {
    id: 'meditations-aurelius',
    slug: 'meditations-marcus-aurelius',
    name: 'Meditations by Marcus Aurelius (Modern Library Edition)',
    brand: 'Modern Library',
    category: 'Philosophy & Books',
    price: 12.00,
    rating: 4.7,
    reviewCount: 15234,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Meditations-New-Translation-Marcus-Aurelius/dp/0812968255?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80'],
    description: 'The timeless Stoic philosophy of Roman Emperor Marcus Aurelius. Essential wisdom on resilience, virtue, and living with purpose. A polymath\'s foundational text.',
    features: [
      'Ancient Stoic Wisdom - Practical philosophy for modern life',
      'Gregory Hays Translation - Accessible, elegant modern English',
      'Personal Reflections - Emperor\'s private journal on virtue',
      'Timeless Principles - Resilience, duty, rationality, acceptance',
    ],
    specs: {
      'Format': 'Paperback',
      'Pages': '254 pages',
      'Publisher': 'Modern Library',
      'Language': 'English',
      'Era': 'Written ~170 AD',
    },
    benefits: [
      'Build mental resilience and emotional control',
      'Cultivate inner peace regardless of external circumstances',
      'Develop rational thinking and perspective',
      'Foundation for Stoic philosophy practice',
    ],
    forWhom: [
      'Philosophers and deep thinkers',
      'Anyone seeking mental clarity and resilience',
      'Leaders and decision-makers',
      'Polymaths building intellectual foundation',
    ],
    featured: true,
  },
  {
    id: 'sapiens',
    slug: 'sapiens-harari',
    name: 'Sapiens: A Brief History of Humankind by Yuval Noah Harari',
    brand: 'Harper Perennial',
    category: 'Philosophy & Books',
    price: 16.99,
    originalPrice: 24.99,
    rating: 4.6,
    reviewCount: 42156,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Sapiens-Humankind-Yuval-Noah-Harari/dp/0062316117?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80'],
    description: 'A sweeping history of humanity from the Stone Age to AI. Harari\'s masterwork connects biology, history, and philosophy into a unified vision of human evolution.',
    features: [
      'Macro-Historical Perspective - 70,000 years of human history',
      'Interdisciplinary Synthesis - Biology, anthropology, economics, philosophy',
      'Big Ideas - Cognitive Revolution, Agricultural Revolution, Scientific Revolution',
      'Future Vision - Where humanity is headed',
    ],
    specs: {
      'Format': 'Paperback',
      'Pages': '464 pages',
      'Publisher': 'Harper Perennial',
      'Language': 'English',
      'Published': '2015 (International Bestseller)',
    },
    benefits: [
      'Understand the deep patterns of human civilization',
      'Connect disparate fields of knowledge',
      'Develop big-picture thinking',
      'Essential for polymaths and systems thinkers',
    ],
    forWhom: [
      'Intellectuals and polymaths',
      'Anyone wanting to understand humanity\'s trajectory',
      'Systems thinkers and futurists',
      'Readers who love connecting big ideas',
    ],
    featured: true,
  },
  {
    id: 'republic-plato',
    slug: 'the-republic-plato',
    name: 'The Republic by Plato',
    brand: 'Penguin Classics',
    category: 'Philosophy & Books',
    price: 14.00,
    rating: 4.5,
    reviewCount: 8934,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Republic-Plato/dp/0140455116?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&q=80'],
    description: 'Plato\'s foundational work on justice, the ideal state, and the philosopher-king. Required reading for anyone exploring political philosophy and ethics.',
    features: [
      'Socratic Dialogues - Interactive exploration of justice',
      'Theory of Forms - Metaphysical foundation of Western philosophy',
      'Allegory of the Cave - Timeless metaphor for enlightenment',
      'Political Philosophy - Blueprint for the ideal state',
    ],
    specs: {
      'Format': 'Paperback',
      'Pages': '416 pages',
      'Publisher': 'Penguin Classics',
      'Translation': 'Desmond Lee',
      'Era': 'Written ~375 BC',
    },
    benefits: [
      'Master classical philosophical argumentation',
      'Understand the foundations of Western political thought',
      'Develop critical thinking and dialectical reasoning',
      'Essential for polymaths studying philosophy',
    ],
    forWhom: [
      'Philosophy students and scholars',
      'Political thinkers and leaders',
      'Anyone building classical education foundation',
      'Polymaths exploring timeless ideas',
    ],
    featured: true,
  },

  // MODEL/LIFESTYLE - NASA & SPACE
  {
    id: 'nasa-hoodie-vintage',
    slug: 'nasa-vintage-hoodie',
    name: 'NASA Vintage Logo Hoodie - Premium Quality',
    brand: 'NASA',
    category: 'Model & Lifestyle',
    price: 39.99,
    rating: 4.7,
    reviewCount: 8234,
    inStock: true,
    amazonUrl: `https://www.amazon.com/NASA-Vintage-Logo-Hoodie-Sweatshirt/dp/B0BQ1ZQXQN?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80'],
    description: 'Iconic NASA "meatball" logo hoodie. Premium quality sweatshirt representing humanity\'s greatest scientific achievement. Perfect blend of style, intellect, and cosmic perspective.',
    features: [
      'Authentic NASA Logo - Classic "meatball" design from space race era',
      'Premium Cotton Blend - Soft, comfortable, durable construction',
      'Unisex Fit - Versatile sizing for all body types',
      'Statement Piece - Represents exploration, science, innovation',
      'Vintage Aesthetic - Timeless design with cultural significance',
    ],
    specs: {
      'Material': '50% Cotton, 50% Polyester',
      'Sizes': 'S, M, L, XL, XXL',
      'Fit': 'Unisex',
      'Care': 'Machine washable',
      'Origin': 'Officially licensed NASA merchandise',
    },
    benefits: [
      'Embody polymath identity - science, exploration, future-thinking',
      'Conversation starter about space, technology, human achievement',
      'High-quality daily wear with intellectual statement',
      'Versatile wardrobe staple with timeless appeal',
    ],
    forWhom: [
      'Polymaths and Renaissance individuals',
      'Science and space enthusiasts',
      'Anyone who values human innovation',
      'People with cosmic perspective on life',
    ],
    featured: true,
  },
  {
    id: 'nasa-shirt-worm',
    slug: 'nasa-worm-logo-shirt',
    name: 'NASA Worm Logo T-Shirt - Retro Space Program',
    brand: 'NASA',
    category: 'Model & Lifestyle',
    price: 24.99,
    rating: 4.6,
    reviewCount: 12456,
    inStock: true,
    amazonUrl: `https://www.amazon.com/NASA-Worm-Logo-T-Shirt-Black/dp/B08XYQH4VG?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80'],
    description: 'The legendary NASA "worm" logo from 1975-1992. Minimalist, futuristic design representing the golden age of space exploration. A polymath\'s aesthetic statement.',
    features: [
      'Iconic Worm Logo - Revolutionary 1970s NASA branding',
      'Soft Cotton - Comfortable, breathable, premium quality',
      'Minimalist Design - Clean, modern, futuristic aesthetic',
      'Cultural Icon - Represents peak human achievement',
      'Multiple Colors - Black, navy, white options',
    ],
    specs: {
      'Material': '100% Cotton',
      'Sizes': 'S, M, L, XL, XXL',
      'Fit': 'Classic unisex',
      'Print': 'High-quality screen print',
      'Official': 'Licensed NASA merchandise',
    },
    benefits: [
      'Minimalist aesthetic with maximum intellectual signaling',
      'Represents space exploration\'s most innovative era',
      'Perfect casual wear for polymaths',
      'Timeless design transcending trends',
    ],
    forWhom: [
      'Design-conscious polymaths',
      'Minimalists who value substance',
      'Space program historians',
      'Anyone appreciating iconic design',
    ],
    featured: true,
  },

  // PLANT CARE
  {
    id: 'spider-farmer-sf1000',
    slug: 'spider-farmer-led-grow-light',
    name: 'Spider Farmer SF1000 LED Grow Light, Full Spectrum for Indoor Plants',
    brand: 'Spider Farmer',
    category: 'Home & Garden',
    price: 109.99,
    rating: 4.7,
    reviewCount: 9234,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Spider-Farmer-Compatible-Spectrum-Hydroponic/dp/B07TS82HX6?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80'],
    description: 'Premium full-spectrum LED grow light for thriving indoor plants. Samsung LM301B diodes deliver optimal PAR output for all growth stages.',
    features: [
      'Samsung LM301B Diodes - Industry-leading efficiency',
      'Full Spectrum - 3000K, 5000K, 660nm, 760nm IR for all stages',
      'High Efficiency - 2.9 µmol/J PPE, lower energy costs',
      'Silent Operation - Fanless design, zero noise',
      'Dimmable - Adjust intensity for seedlings to flowering',
    ],
    specs: {
      'Power Draw': '100W',
      'PPF': '290 µmol/s',
      'Coverage': '2x2 ft (veg), 1.5x1.5 ft (flower)',
      'Diodes': '1016 Samsung LM301B LEDs',
      'Lifespan': '50,000+ hours',
      'Dimensions': '12.4 x 10.6 x 2.2 inches',
    },
    benefits: [
      'Year-round indoor gardening regardless of climate',
      'Healthier, faster-growing plants',
      '50% more energy efficient than HPS/MH lights',
      'Perfect for herbs, vegetables, succulents, flowers',
    ],
    forWhom: [
      'Indoor plant enthusiasts',
      'Urban gardeners with limited natural light',
      'Herb and vegetable growers',
      'Anyone serious about plant health',
    ],
    featured: true,
  },

  // PREMIUM TECH & AUDIO
  {
    id: 'airpods-max',
    slug: 'airpods-max',
    name: 'Apple AirPods Max - Wireless Over-Ear Headphones',
    brand: 'Apple',
    category: 'Premium Tech',
    price: 549.00,
    rating: 4.7,
    reviewCount: 18234,
    inStock: true,
    amazonUrl: `https://www.amazon.com/New-Apple-AirPods-Max-Silver/dp/B08PZHYWJS?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=800&q=80'],
    description: `Apple AirPods Max combine sophisticated design with breakthrough audio technology. Featuring computational audio, Adaptive EQ, and Active Noise Cancellation, these premium over-ear headphones deliver an unparalleled listening experience for deep work, creative sessions, and immersive content consumption.`,
    features: [
      'Computational Audio - Apple H1 chip powers advanced audio features',
      'Adaptive EQ - Real-time tuning to fit your ear shape',
      'Active Noise Cancellation - Block out the world for deep focus',
      'Transparency Mode - Hear your surroundings when needed',
      'Spatial Audio - Immersive 3D sound with dynamic head tracking',
      'Premium Materials - Stainless steel frame, memory foam ear cushions',
      '20-Hour Battery - All-day listening with ANC enabled',
      'Seamless Apple Integration - Instant switching across all Apple devices',
    ],
    specs: {
      'Driver': 'Custom 40mm dynamic driver',
      'Connectivity': 'Bluetooth 5.0',
      'Battery Life': '20 hours (ANC/Transparency), 22 hours (regular)',
      'Charging': 'Lightning port, fast charge (5min = 1.5hrs)',
      'Weight': '384.8g',
      'Colors': 'Silver, Space Gray, Sky Blue, Pink, Green',
      'Compatibility': 'iPhone, iPad, Mac, Apple TV, Apple Watch',
      'In the Box': 'AirPods Max, Smart Case, Lightning cable',
    },
    benefits: [
      'Deep Focus - Industry-leading ANC eliminates distractions',
      'Studio-Quality Sound - Computational audio rivals professional headphones',
      'All-Day Comfort - Memory foam cushions for extended wear',
      'Premium Build - Luxury materials built to last decades',
      'Ecosystem Integration - Seamless switching between Apple devices',
      'Spatial Audio - Immersive movie and music experience',
      'Future-Proof - Regular software updates add new features',
    ],
    forWhom: [
      'Creative professionals seeking studio-quality audio',
      'Deep work practitioners who need absolute focus',
      'Polymaths juggling multiple devices and workflows',
      'Music lovers who appreciate audiophile-grade sound',
      'Content creators editing audio and video',
      'Apple ecosystem users wanting seamless integration',
      'Anyone who values premium build quality and longevity',
    ],
    featured: true,
  },
  {
    id: 'ipad-pro-13-m4',
    slug: 'ipad-pro-13-m4',
    name: 'Apple iPad Pro 13-inch (M4) - Ultimate Creative Canvas',
    brand: 'Apple',
    category: 'Premium Tech',
    price: 1299.00,
    rating: 4.8,
    reviewCount: 3452,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Apple-iPad-Pro-13-Inch-Landscape/dp/B0D3J7FCFH?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80'],
    description: `The most advanced iPad ever. M4 chip delivers desktop-class performance in an impossibly thin design. Pro camera system, Ultra Retina XDR display, and Apple Pencil Pro support make this the ultimate tool for polymaths - from digital art to code to content creation.`,
    features: [
      'M4 Chip - Desktop-class performance with AI acceleration',
      'Ultra Retina XDR Display - Tandem OLED technology, 1600 nits peak HDR',
      'ProMotion 120Hz - Buttery smooth scrolling and responsive Apple Pencil',
      'Apple Pencil Pro Support - Squeeze, barrel roll, hover for precision',
      'Thunderbolt / USB 4 - Pro-level connectivity and external display support',
      'Face ID - Secure authentication in any orientation',
      '12MP Ultra Wide Camera - Center Stage keeps you in frame',
      'All-Day Battery - Up to 10 hours of web browsing',
    ],
    specs: {
      'Processor': 'Apple M4 chip, 10-core CPU, 10-core GPU',
      'Display': '13-inch Ultra Retina XDR (2752x2064), ProMotion 120Hz',
      'Storage': '256GB, 512GB, 1TB, 2TB',
      'Memory': '8GB or 16GB unified memory',
      'Cameras': '12MP Wide, 10MP Ultra Wide, LiDAR Scanner',
      'Connectivity': 'Wi-Fi 6E, Bluetooth 5.3, USB-C Thunderbolt',
      'Weight': '579g (Wi-Fi), 582g (Wi-Fi + Cellular)',
      'Thickness': '5.1mm - thinnest Apple product ever',
    },
    benefits: [
      'Ultimate Versatility - Laptop replacement, creative canvas, reading device',
      'Desktop Power - Edit 4K video, run professional apps, code complex projects',
      'Infinite Canvas - Digital art with Apple Pencil Pro rivals pen on paper',
      'Portable Workstation - Desktop performance in a 1.3lb package',
      'Professional Photography - ProRAW editing on stunning XDR display',
      'Content Creation Hub - Record, edit, publish from one device',
      'Long-Term Investment - M4 chip ensures 5+ years of peak performance',
    ],
    forWhom: [
      'Digital artists and illustrators using Procreate',
      'Photographers editing RAW files on location',
      'Developers coding with Swift Playgrounds',
      'Content creators producing videos and podcasts',
      'Polymaths who need one device for everything',
      'Students taking handwritten notes with Apple Pencil',
      'Anyone seeking the ultimate creative tablet',
    ],
    featured: true,
  },
  {
    id: 'sony-wh-1000xm5',
    slug: 'sony-wh-1000xm5-headphones',
    name: 'Sony WH-1000XM5 - Industry-Leading Noise Canceling Headphones',
    brand: 'Sony',
    category: 'Premium Tech',
    price: 398.00,
    originalPrice: 449.99,
    rating: 4.7,
    reviewCount: 24183,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Sony-WH-1000XM5-Canceling-Headphones-Hands-Free/dp/B09XS7JWHH?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80'],
    description: `Sony's flagship noise-canceling headphones set the industry standard. With two processors controlling 8 microphones, adaptive sound, and 30-hour battery life, the WH-1000XM5 delivers unparalleled focus and audio quality for professionals and audiophiles.`,
    features: [
      'Industry-Leading ANC - Dual-processor, 8-microphone system for superior noise cancellation',
      '30-Hour Battery - All-day listening with quick charge (3min = 3hrs)',
      'Adaptive Sound Control - Automatically adjusts to your activity and environment',
      'Multipoint Connection - Simultaneously connect to two Bluetooth devices',
      'Speak-to-Chat - Automatically pauses music when you start talking',
      'Premium Comfort - Redesigned lightweight design with soft leather cushions',
      'Hi-Res Audio Wireless - LDAC codec for studio-quality sound',
      'Precision Voice Pickup - 4 beamforming mics isolate your voice for crystal-clear calls',
    ],
    specs: {
      'Driver': '30mm dynamic driver',
      'Frequency Response': '4Hz - 40,000Hz',
      'Battery Life': '30 hours (ANC on), 40 hours (ANC off)',
      'Charging': 'USB-C, quick charge (3min = 3hrs)',
      'Weight': '250g (lighter than previous model)',
      'Connectivity': 'Bluetooth 5.2, LDAC, AAC, SBC',
      'Controls': 'Touch sensor, voice assistant, wearing detection',
      'Foldable': 'Yes, with premium carrying case',
    },
    benefits: [
      'Best-in-Class ANC - Silence distractions for deep focus and productivity',
      'All-Day Comfort - 250g lightweight design for extended wear',
      'Premium Audio - LDAC support for Hi-Res audio quality',
      'Travel Essential - Folds flat, 30-hour battery perfect for long flights',
      'Seamless Switching - Multipoint connection for work and personal devices',
      'Future-Proof - Regular software updates via Sony Headphones app',
      'Professional Calls - Beamforming mics ensure clear communication',
    ],
    forWhom: [
      'Professionals working in noisy environments',
      'Frequent travelers needing all-day battery',
      'Audiophiles who demand Hi-Res audio quality',
      'Remote workers on constant video calls',
      'Students studying in cafes or libraries',
      'Anyone seeking the best ANC on the market',
      'Multi-device users who switch between phone and laptop',
    ],
    featured: true,
  },
  {
    id: 'apple-watch-ultra-2',
    slug: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2 - Most Rugged and Capable Apple Watch',
    brand: 'Apple',
    category: 'Premium Tech',
    price: 799.00,
    rating: 4.8,
    reviewCount: 8934,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Apple-Watch-Ultra-GPS-Cellular/dp/B0CHX3PQXY?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&q=80'],
    description: `Apple Watch Ultra 2 is engineered for endurance, exploration, and peak performance. Featuring titanium case, the brightest Apple display ever (3000 nits), precision dual-frequency GPS, and up to 36 hours of battery life - the ultimate tool for serious athletes and adventurers.`,
    features: [
      'S9 SiP - Faster processor with on-device Siri and precise health tracking',
      'Brightest Display - 3000 nits, readable in direct sunlight',
      'Titanium Case - Aerospace-grade titanium, corrosion-resistant',
      'Dual-Frequency GPS - Most accurate GPS in a smartwatch',
      'Action Button - Customizable instant control for workouts, waypoints, more',
      'Depth Gauge - Water temperature and depth up to 40m for diving',
      '86dB Siren - Emergency siren audible up to 180m away',
      '36-Hour Battery - Up to 72 hours in Low Power Mode',
    ],
    specs: {
      'Display': '49mm Retina LTPO OLED, sapphire crystal, 3000 nits',
      'Case': 'Titanium, water resistant to 100m, MIL-STD 810H',
      'GPS': 'Precision dual-frequency (L1 and L5)',
      'Connectivity': 'GPS + Cellular, Wi-Fi 4, Bluetooth 5.3, Ultra Wideband',
      'Sensors': 'Blood oxygen, ECG, heart rate, temperature, depth, altimeter',
      'Battery': 'Up to 36 hours normal use, 72 hours low power mode',
      'Operating Temperature': '-20°C to 55°C',
      'Band Compatibility': 'Alpine Loop, Trail Loop, Ocean Band (49mm)',
    },
    benefits: [
      'Extreme Durability - Built for the toughest conditions',
      'Precision Fitness - Advanced metrics for serious athletes',
      'Adventure Ready - Depth gauge, GPS waypoints, emergency siren',
      'All-Day Battery - 36 hours without compromising features',
      'Health Guardian - Blood oxygen, ECG, fall detection, crash detection',
      'Always-On Display - Brightest screen ever, readable in any light',
      'Titanium Build - Lightweight yet incredibly strong',
    ],
    forWhom: [
      'Endurance athletes training for marathons, ultras, triathlons',
      'Outdoor adventurers hiking, climbing, diving',
      'Health-conscious individuals tracking vitals 24/7',
      'Professionals who need reliable all-day battery',
      'Travelers navigating unfamiliar terrain',
      'Emergency responders needing rugged, dependable tech',
      'Anyone seeking the most capable smartwatch ever made',
    ],
    featured: true,
  },

  // LUXURY LIFESTYLE & QUALITY
  {
    id: 'yeti-rambler-30oz',
    slug: 'yeti-rambler-30oz',
    name: 'YETI Rambler 30 oz Tumbler with MagSlider Lid',
    brand: 'YETI',
    category: 'Luxury Lifestyle',
    price: 38.00,
    rating: 4.9,
    reviewCount: 87234,
    inStock: true,
    amazonUrl: `https://www.amazon.com/YETI-Rambler-Vacuum-Insulated-Stainless/dp/B073WJQRGR?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80'],
    description: `The YETI Rambler 30 oz is the gold standard in premium insulated drinkware. Double-wall vacuum insulation keeps drinks ice-cold (or piping hot) for hours. Built with kitchen-grade 18/8 stainless steel, this tumbler is virtually indestructible and designed for a lifetime of use.`,
    features: [
      'Double-Wall Vacuum Insulation - Keeps drinks cold for 7+ hours, hot for 3+ hours',
      'Kitchen-Grade Stainless Steel - 18/8 stainless steel, puncture and rust-resistant',
      'MagSlider Lid - Magnetic slider for easy opening, leak-resistant seal',
      'No Sweat Design - Stays dry on the outside, no condensation rings',
      'Dishwasher Safe - Easy to clean, built to last a lifetime',
      'Fits Cup Holders - Designed to fit most vehicle cup holders',
      'BPA-Free - Food-safe materials throughout',
      'Wide Mouth - Easy to fill, pour, and add ice cubes',
    ],
    specs: {
      'Capacity': '30 oz (887 ml)',
      'Material': '18/8 stainless steel, BPA-free plastic lid',
      'Insulation': 'Double-wall vacuum insulation',
      'Dimensions': '3.5" W x 7.875" H',
      'Weight': '1.2 lbs (544g)',
      'Dishwasher Safe': 'Yes',
      'Warranty': '5-year manufacturer warranty',
      'Made In': 'China (to YETI quality standards)',
    },
    benefits: [
      'All-Day Hydration - 30 oz capacity keeps you hydrated longer',
      'Temperature Control - Ice stays frozen, coffee stays hot for hours',
      'Built to Last - Lifetime durability, no degradation over time',
      'Premium Feel - Heavy, solid construction feels expensive',
      'Versatile Use - Coffee, water, smoothies, cocktails - anything',
      'Zero Condensation - Desk stays dry, no water rings',
      'Investment Quality - Replace disposable cups forever',
    ],
    forWhom: [
      'Professionals keeping coffee hot through long work sessions',
      'Athletes and fitness enthusiasts staying hydrated',
      'Commuters who need drinks to last the whole journey',
      'Anyone who appreciates quality, durable everyday items',
      'Environmentally conscious individuals reducing waste',
      'People tired of lukewarm coffee or melted ice',
      'Quality-focused individuals who buy once, use forever',
    ],
    featured: true,
  },
  {
    id: 'kindle-oasis',
    slug: 'kindle-oasis',
    name: 'Kindle Oasis - Premium E-Reader with 7-inch Display',
    brand: 'Amazon',
    category: 'Luxury Lifestyle',
    price: 249.99,
    rating: 4.5,
    reviewCount: 14832,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Kindle-Oasis-adjustable-warm-light/dp/B07L5GDTYY?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80'],
    description: `The Kindle Oasis is Amazon's most premium e-reader, designed for serious readers and intellectuals. With a 7-inch high-resolution display, adjustable warm light, and ergonomic design, the Oasis delivers a reading experience that rivals physical books while offering the convenience of carrying thousands of titles.`,
    features: [
      '7-inch Glare-Free Display - 300 PPI resolution, reads like real paper',
      'Adjustable Warm Light - 25 LEDs for perfect reading in any light',
      'Ergonomic Design - Thin, lightweight with page turn buttons',
      'Waterproof (IPX8) - Read in the bath, by the pool, at the beach',
      'Massive Storage - 8GB or 32GB holds thousands of books',
      'Weeks of Battery Life - Single charge lasts weeks, not days',
      'Audible Integration - Pair with Bluetooth headphones for audiobooks',
      'Premium Build - Aluminum back, flush-front design',
    ],
    specs: {
      'Display': '7" E Ink Carta 1200, 300 PPI, 16 levels of gray',
      'Lighting': '25 LEDs, adjustable warmth (cool white to amber)',
      'Storage': '8GB (~3,500 books) or 32GB (~15,000 books)',
      'Connectivity': 'Wi-Fi or Wi-Fi + Free Cellular',
      'Battery': 'Up to 6 weeks (30 min/day, wireless off)',
      'Waterproof': 'IPX8 rated (up to 2 meters for 60 minutes)',
      'Weight': '6.8 oz (194g)',
      'Dimensions': '6.3" x 5.6" x 0.13-0.33"',
    },
    benefits: [
      'Eye-Friendly Reading - No glare, reads like paper, not a screen',
      'Portable Library - Carry thousands of books in 6.8 oz',
      'Perfect Lighting - Read in bright sunlight or complete darkness',
      'Waterproof Freedom - Read anywhere without worry',
      'Long Battery Life - Charge once a month, not once a day',
      'Premium Experience - Feels like holding a luxury hardcover',
      'Investment in Knowledge - Makes reading effortless and enjoyable',
    ],
    forWhom: [
      'Voracious readers consuming multiple books per month',
      'Philosophers and intellectuals building vast libraries',
      'Travelers wanting to pack light with unlimited reading',
      'Students reading textbooks and research papers',
      'Bath and pool readers who need waterproof devices',
      'Anyone with limited physical book storage space',
      'People who value premium, thoughtfully designed products',
    ],
    featured: true,
  },
  {
    id: 'moleskine-classic-notebook',
    slug: 'moleskine-classic-notebook',
    name: 'Moleskine Classic Notebook - Large, Hard Cover, Ruled',
    brand: 'Moleskine',
    category: 'Luxury Lifestyle',
    price: 22.95,
    rating: 4.7,
    reviewCount: 32418,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Moleskine-Classic-Notebook-Hard-Cover/dp/8883701127?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80'],
    description: `The legendary Moleskine notebook, favored by artists, writers, and thinkers for over two centuries. With acid-free paper, elastic closure, ribbon bookmark, and expandable inner pocket, the Moleskine Classic is the gold standard for analog note-taking and journaling.`,
    features: [
      'Premium Ivory Paper - 240 ruled pages, acid-free, 70 gsm',
      'Hard Cover - Durable cardboard-bound cover built to last',
      'Elastic Closure - Keeps notebook securely closed in bags',
      'Ribbon Bookmark - Never lose your place',
      'Expandable Inner Pocket - Store notes, cards, receipts',
      'Thread-Bound - Pages lie flat when open for comfortable writing',
      'Large Size - 5" x 8.25" provides ample writing space',
      'Iconic Design - The notebook of Hemingway, Picasso, Van Gogh',
    ],
    specs: {
      'Size': 'Large (5" x 8.25")',
      'Pages': '240 ruled pages',
      'Paper': 'Ivory 70 gsm, acid-free',
      'Cover': 'Hard cardboard-bound cover',
      'Binding': 'Thread-bound, lays flat',
      'Closure': 'Elastic band',
      'Extras': 'Ribbon bookmark, expandable pocket',
      'Made In': 'Italy (Moleskine heritage)',
    },
    benefits: [
      'Timeless Design - Over 200 years of creative history',
      'Quality Construction - Built to preserve your ideas for decades',
      'Portable Thinking Tool - Fits in bags, always accessible',
      'Distraction-Free - Analog focus without digital interruptions',
      'Premium Feel - Heavy paper, satisfying to write on',
      'Creative Freedom - Blank canvas for ideas, sketches, plans',
      'Legacy Format - Create something you\'ll treasure forever',
    ],
    forWhom: [
      'Writers and authors drafting novels and essays',
      'Philosophers journaling thoughts and reflections',
      'Artists sketching ideas and concepts',
      'Students taking notes in lectures and seminars',
      'Professionals brainstorming and planning projects',
      'Anyone who thinks better with pen and paper',
      'People building a legacy of written thought',
    ],
    featured: true,
  },
  {
    id: 'rocketbook-everlast',
    slug: 'rocketbook-everlast',
    name: 'Rocketbook Everlast Smart Reusable Notebook',
    brand: 'Rocketbook',
    category: 'Luxury Lifestyle',
    price: 34.00,
    rating: 4.4,
    reviewCount: 29847,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Rocketbook-Everlast-Reusable-Smart-Notebook/dp/B071Y3MSRK?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&q=80'],
    description: `Rocketbook Everlast combines the joy of handwriting with digital organization. Write naturally with the included Pilot FriXion pen, scan with the Rocketbook app, then erase with a damp cloth. Your notes are backed up to cloud services while you reuse the same notebook infinitely.`,
    features: [
      'Infinitely Reusable - Write, scan, erase with damp cloth, repeat forever',
      'Cloud Integration - Auto-send to Google Drive, Dropbox, Evernote, Slack, Email',
      'Pilot FriXion Pen - Included pen erases cleanly with water',
      'AI-Powered OCR - Handwriting becomes searchable digital text',
      'Smart Symbols - Quick send to specific cloud destinations',
      '42 Dot-Grid Pages - Versatile for writing, sketching, diagrams',
      'Mobile App - Free iOS/Android app for scanning and organization',
      'Eco-Friendly - Replaces thousands of paper notebooks',
    ],
    specs: {
      'Size': 'Letter (8.5" x 11")',
      'Pages': '42 reusable dot-grid pages',
      'Material': 'Polyester composite pages',
      'Included': '1 Pilot FriXion pen, microfiber cloth',
      'App': 'Free iOS/Android Rocketbook app',
      'Cloud Services': 'Google Drive, Dropbox, Evernote, Box, OneNote, Slack, iCloud, Email',
      'OCR': 'Handwriting-to-text conversion',
      'Reusability': 'Unlimited with proper care',
    },
    benefits: [
      'Best of Both Worlds - Handwrite like analog, organize like digital',
      'Zero Paper Waste - One notebook replaces thousands of pages',
      'Instant Backup - Never lose notes, everything auto-saved to cloud',
      'Searchable Notes - Find anything instantly with OCR text search',
      'Cost Effective - Pay once, use forever',
      'Organized Chaos - Smart symbols route notes to right destinations',
      'Polymath Perfect - Seamlessly blend analog thinking with digital systems',
    ],
    forWhom: [
      'Digital nomads who want analog feel with digital organization',
      'Students who handwrite notes but need them digitized',
      'Professionals in paperless offices',
      'Environmentally conscious note-takers',
      'Polymaths organizing thoughts across multiple projects',
      'Anyone who loves writing by hand but hates clutter',
      'Tech-forward thinkers blending old and new methods',
    ],
    featured: true,
  },
  // CLEAN LIVING & WELLNESS
  {
    id: 'dr-bronners-eucalyptus',
    slug: 'dr-bronners-eucalyptus-castile-soap',
    name: "Dr. Bronner's Pure-Castile Liquid Soap - Eucalyptus",
    brand: "Dr. Bronner's",
    category: 'Lifestyle',
    price: 18.99,
    rating: 4.8,
    reviewCount: 45283,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Dr-Bronners-Pure-Castile-Liquid-Soap/dp/B0016BFD4K?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    description: `Dr. Bronner's Eucalyptus Pure-Castile Liquid Soap delivers an invigorating, energizing clean for body, home, and everything in between. Made with certified organic oils and no synthetic detergents or preservatives, this 18-in-1 soap replaces most cleaning products in your home while being safe enough for sensitive skin and gentle on the planet.`,
    features: [
      '18-in-1 Uses - Body, face, hair, dishes, laundry, floors, pets, and more',
      'Certified Organic Oils - Coconut, olive, jojoba, and hemp seed oils',
      'Eucalyptus Essential Oil - Invigorating scent that energizes your morning',
      'Concentrated Formula - A little goes a long way, dilute for various uses',
      'No Synthetic Ingredients - Free of foaming agents, preservatives, and artificial fragrances',
      'Vegan & Cruelty-Free - Never tested on animals, no animal products',
      'Biodegradable - Safe for greywater systems and septic tanks',
      'Fair Trade Certified - Ethical sourcing of all ingredients',
    ],
    specs: {
      'Size': '32 fl oz',
      'Form': 'Liquid soap',
      'Scent': 'Eucalyptus',
      'Ingredients': 'Water, Organic Coconut Oil, Potassium Hydroxide, Organic Olive Oil, Organic Hemp Oil, Organic Jojoba Oil, Eucalyptus Oil, Citric Acid, Tocopherol',
      'Certifications': 'USDA Organic, Fair Trade, Leaping Bunny, Non-GMO',
      'pH': 'Naturally alkaline (~9)',
      'Made In': 'USA',
    },
    benefits: [
      'Chemical-Free Living - Replace toxic cleaners with one safe product',
      'Morning Energy Boost - Eucalyptus awakens your senses and clears your mind',
      'Cancer Prevention - No carcinogens, endocrine disruptors, or synthetic chemicals',
      'Multi-Purpose Value - One bottle replaces shampoo, body wash, dish soap, and more',
      'Sensitive Skin Safe - Gentle enough for babies and those with allergies',
      'Eco-Conscious - Minimal packaging, biodegradable, sustainably sourced',
      'Cost Effective - Concentrated formula lasts months with proper dilution',
      'Peace of Mind - Know exactly what touches your skin and enters your home',
    ],
    forWhom: [
      'Health-conscious individuals avoiding synthetic chemicals',
      'Those concerned about cancer-causing ingredients in everyday products',
      'Minimalists who want one product for multiple uses',
      'People with sensitive skin or allergies',
      'Environmentally conscious consumers',
      'Anyone seeking an energizing morning shower experience',
      'Parents wanting safe products for their family',
      'Those building a chemical-free home',
    ],
    featured: false,
  },
  {
    id: 'dr-bronners-lavender',
    slug: 'dr-bronners-lavender-castile-soap',
    name: "Dr. Bronner's Pure-Castile Liquid Soap - Lavender",
    brand: "Dr. Bronner's",
    category: 'Lifestyle',
    price: 18.99,
    rating: 4.8,
    reviewCount: 52847,
    inStock: true,
    amazonUrl: `https://www.amazon.com/Dr-Bronners-Pure-Castile-Liquid-Soap/dp/B0009R16MA?tag=${AFFILIATE_TAG}`,
    images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80'],
    description: `Dr. Bronner's Lavender Pure-Castile Liquid Soap provides a calming, relaxing clean perfect for evening baths and unwinding after a long day. Made with certified organic oils and pure lavender essential oil, this 18-in-1 soap soothes body and mind while cleaning dishes, laundry, and surfaces without harsh chemicals.`,
    features: [
      '18-in-1 Uses - Body, face, hair, dishes, laundry, floors, pets, and more',
      'Certified Organic Oils - Coconut, olive, jojoba, and hemp seed oils',
      'Lavender Essential Oil - Calming scent perfect for relaxation and sleep',
      'Concentrated Formula - Dilute for body wash, household cleaning, and more',
      'No Synthetic Ingredients - Free of foaming agents, preservatives, and artificial fragrances',
      'Vegan & Cruelty-Free - Never tested on animals, no animal products',
      'Biodegradable - Safe for greywater systems and septic tanks',
      'Fair Trade Certified - Ethical sourcing of all ingredients',
    ],
    specs: {
      'Size': '32 fl oz',
      'Form': 'Liquid soap',
      'Scent': 'Lavender',
      'Ingredients': 'Water, Organic Coconut Oil, Potassium Hydroxide, Organic Olive Oil, Organic Hemp Oil, Organic Jojoba Oil, Lavandin Extract, Lavender Oil, Citric Acid, Tocopherol',
      'Certifications': 'USDA Organic, Fair Trade, Leaping Bunny, Non-GMO',
      'pH': 'Naturally alkaline (~9)',
      'Made In': 'USA',
    },
    benefits: [
      'Chemical-Free Living - Replace toxic cleaners with one safe product',
      'Evening Relaxation - Lavender calms the mind and prepares you for restful sleep',
      'Cancer Prevention - No carcinogens, endocrine disruptors, or synthetic chemicals',
      'Multi-Purpose Value - One bottle replaces shampoo, body wash, dish soap, and more',
      'Sensitive Skin Safe - Gentle enough for babies and those with allergies',
      'Eco-Conscious - Minimal packaging, biodegradable, sustainably sourced',
      'Cost Effective - Concentrated formula lasts months with proper dilution',
      'Aromatherapy Benefits - Pure essential oil provides natural calming effects',
    ],
    forWhom: [
      'Health-conscious individuals avoiding synthetic chemicals',
      'Those concerned about cancer-causing ingredients in everyday products',
      'People seeking better sleep and relaxation',
      'Minimalists who want one product for multiple uses',
      'People with sensitive skin or allergies',
      'Environmentally conscious consumers',
      'Parents wanting safe products for their family',
      'Anyone building a chemical-free, wellness-focused home',
    ],
    featured: false,
  },
]

export function getProductBySlug(slug: string): AffiliateProduct | undefined {
  return affiliateProducts.find((p) => p.slug === slug)
}

export function getFeaturedProducts(): AffiliateProduct[] {
  return affiliateProducts.filter((p) => p.featured)
}

export function getProductsByCategory(category: string): AffiliateProduct[] {
  return affiliateProducts.filter((p) => p.category === category)
}

export function buildAffiliateUrl(baseUrl: string): string {
  const url = new URL(baseUrl)
  url.searchParams.set('tag', AFFILIATE_TAG)
  return url.toString()
}
