-- Migration 001: Initial Orders Schema
-- Creates the orders table for production-ready order storage

-- Enable UUID extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create orders table
CREATE TABLE IF NOT EXISTS orders (
  -- Primary identification
  id VARCHAR(255) PRIMARY KEY,

  -- Stripe references
  stripe_session_id VARCHAR(255) NOT NULL UNIQUE,
  stripe_payment_intent_id VARCHAR(255),

  -- Customer information
  customer_email VARCHAR(255) NOT NULL,
  customer_name VARCHAR(255) NOT NULL,

  -- Addresses (stored as JSONB for flexibility)
  shipping_address JSONB,
  billing_address JSONB,

  -- Order details
  items JSONB NOT NULL,
  total_amount DECIMAL(10, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'usd',

  -- Status tracking
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  printful_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  printful_order_id VARCHAR(255),

  -- Additional data
  metadata JSONB,

  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_stripe_session ON orders(stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_orders_printful_status ON orders(printful_status);

-- Create composite indexes for filtered queries
CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_email_created ON orders(customer_email, created_at DESC);

-- Add check constraints for data integrity
ALTER TABLE orders
  ADD CONSTRAINT check_total_amount_positive CHECK (total_amount >= 0),
  ADD CONSTRAINT check_status_valid CHECK (status IN ('pending', 'paid', 'fulfilled', 'shipped', 'delivered', 'cancelled')),
  ADD CONSTRAINT check_printful_status_valid CHECK (printful_status IN ('pending', 'processing', 'completed', 'failed')),
  ADD CONSTRAINT check_currency_length CHECK (length(currency) = 3);

-- Create a function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
DROP TRIGGER IF EXISTS update_orders_updated_at ON orders;
CREATE TRIGGER update_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create a view for order summaries (for performance)
CREATE OR REPLACE VIEW order_summaries AS
SELECT
  id,
  customer_email,
  customer_name,
  total_amount,
  currency,
  status,
  printful_status,
  created_at,
  updated_at
FROM orders
ORDER BY created_at DESC;

-- Grant necessary permissions (adjust based on your setup)
-- GRANT SELECT, INSERT, UPDATE ON orders TO your_app_user;
-- GRANT SELECT ON order_summaries TO your_app_user;

-- Add comments for documentation
COMMENT ON TABLE orders IS 'Stores all e-commerce orders from Stripe checkout sessions';
COMMENT ON COLUMN orders.id IS 'Unique order identifier generated by the application';
COMMENT ON COLUMN orders.stripe_session_id IS 'Stripe checkout session ID (unique)';
COMMENT ON COLUMN orders.stripe_payment_intent_id IS 'Stripe payment intent ID for tracking payments';
COMMENT ON COLUMN orders.customer_email IS 'Customer email address for order communication';
COMMENT ON COLUMN orders.shipping_address IS 'Shipping address in JSONB format';
COMMENT ON COLUMN orders.items IS 'Array of order items in JSONB format';
COMMENT ON COLUMN orders.total_amount IS 'Total order amount in the specified currency';
COMMENT ON COLUMN orders.status IS 'Order fulfillment status (pending, paid, fulfilled, shipped, delivered, cancelled)';
COMMENT ON COLUMN orders.printful_status IS 'Printful integration status (pending, processing, completed, failed)';
COMMENT ON COLUMN orders.metadata IS 'Additional order metadata in JSONB format';
